version: '3.8'

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
    container_name: es01
    environment:
      - bootstrap.memory_lock=true # 停用 memory page swap
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m" # JVM args
      - CERT_PASSWORD=${CERT_PASSWORD}
      - ES_PASSWORD=${ES_PASSWORD}
      - KIBANA_PASSWORD=${KIBANA_PASSWORD}
      - ELK_VERSION=${ELK_VERSION}
    ulimits:
      memlock:
        soft: -1
        hard: -1 # 最大可鎖定的memory量，-1是無限制
    volumes:
      - ./es/es_01.yml:/usr/share/elasticsearch/config/elasticsearch.yml 
      - ./certs:/usr/share/elasticsearch/config/certs
      - esdata01:/usr/share/elasticsearch/data
      - ./shell:/shell
      - ./es/plugins/elasticsearch-analysis-ik-${ELK_VERSION}:/usr/share/elasticsearch/plugins/elasticsearch-analysis-ik-${ELK_VERSION} # source: https://release.infinilabs.com/analysis-ik/stable/
    ports:
      - "${ES_PORT}:9200" # for clients (LogStash, Kibana...etc)
      - "9300:9300" # for connection between cluster nodes
    networks:
      - esnet
    command: /bin/bash -c "/shell/init_ik.sh && /shell/init_es.sh"

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
    container_name: es02
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - CERT_PASSWORD=${CERT_PASSWORD}
      - ELK_VERSION=${ELK_VERSION}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./es/es_02.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./certs:/usr/share/elasticsearch/config/certs
      - esdata02:/usr/share/elasticsearch/data
      - ./shell:/shell
      - ./es/plugins/elasticsearch-analysis-ik-${ELK_VERSION}:/usr/share/elasticsearch/plugins/elasticsearch-analysis-ik-${ELK_VERSION}
    networks:
      - esnet

  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
    container_name: es03
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - CERT_PASSWORD=${CERT_PASSWORD}
      - ELK_VERSION=${ELK_VERSION}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./es/es_03.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./certs:/usr/share/elasticsearch/config/certs
      - esdata03:/usr/share/elasticsearch/data
      - ./shell:/shell
      - ./es/plugins/elasticsearch-analysis-ik-${ELK_VERSION}:/usr/share/elasticsearch/plugins/elasticsearch-analysis-ik-${ELK_VERSION}
    networks:
      - esnet

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELK_VERSION}
    container_name: kibana
    environment:
      - ES_HOST=http://es01:${ES_PORT}
      - ES_ROOT_USERNAME=elastic
      - ES_ROOT_PASSWORD=${ES_PASSWORD}
      - ES_USERNAME=kibana_system
      - ES_PASSWORD=${KIBANA_PASSWORD}
      - ES_PORT=${ES_PORT}
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
      - ./shell:/shell
    ports:
      - "${KIBANA_PORT}:5601" # 可開啟Kibana GUI
    networks:
      - esnet
    # depends_on:
    #   es01:
    #     condition: service_healthy
    command: /bin/bash -c "/shell/set_kibana.sh && /usr/share/kibana/bin/kibana"

  logstash:
    image: docker.elastic.co/logstash/logstash:${ELK_VERSION}
    container_name: logstash
    environment:
      - LOGSTASH_JAVA_OPTS=-Xms128m -Xmx128m
      - ES_HOST=http://es01:${ES_PORT}
      - ES_ROOT_USERNAME=elastic
      - ES_ROOT_PASSWORD=${ES_PASSWORD}
      - ES_USERNAME=logstash_internal
      - ES_PASSWORD=${LOGSTASH_PASSWORD}
      - ES_PORT=${ES_PORT}
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./shell:/shell
      - ./log-data:/dlq-storage
    ports:
      - "${LOGSTASH_PORT}:5044" # data source input
      - "9600:9600" # Logstash monitoring
    networks:
      - esnet
    command: /bin/bash -c "/shell/set_logstash.sh && /usr/share/logstash/bin/logstash"

  # pubsub-emulator:
  #   image: google/cloud-sdk:latest
  #   container_name: pubsub-emulator
  #   # platform: linux/arm64/v7 # 沒有arm64的，只能用amd64
  #   command: gcloud beta emulators pubsub start --host-port=0.0.0.0:${PUBSUB_PORT}
  #   ports:
  #     - "${PUBSUB_PORT}:${PUBSUB_PORT}"
  #   environment:
  #     - PUBSUB_PROJECT_ID=${PUBSUB_PROJECT_ID}
  #   networks:
  #     - esnet

volumes:
  esdata01:
    driver: local
  esdata02:
    driver: local
  esdata03:
    driver: local

networks:
  esnet:
    driver: bridge