api:
  environment: dev
  ssl:
    enabled: false
  http:
    host: 127.0.0.1

pipeline:
  id: pubsub-log
  buffer:
    type: direct # 未來版本(9.x) 才能改成heap
  batch:
    size: 500
    delay: 20
  unsafe_shutdown: false

queue:
  type: persisted

dead_letter_queue:
  enable: true
  max_bytes: 1024mb
  storage_policy: drop_older

path:
  dead_letter_queue: "/persist-storage"

# xpack.monitoring已經於7.9.0 deprecated，不用設定